### POST craete customer

POST http://dev.local/nodeone/customers HTTP/1.1
content-type: application/json

{
    "name": "AnewStart",
    "course": "TestingAPI",
    "statusId": 1,
    "officeId":2
}

###
PUT http://dev.local/nodeone/customers/6 HTTP/1.1
content-type: application/json

{
    "name": "Katie",
    "course": "Dog Training",
    "statusId": 1,
    "officeId": 1
}

###
GET http://dev.local/nodeone/customers

###
GET http://dev.local/nodeone/customers/6