### POST craete customer

POST http://localhost/nodeone/customers HTTP/1.1
content-type: application/json

{
    "name": "Testing This",
    "course": "Abrakadabra",
    "active": 1,
    "officeId":2
}

###
PUT http://localhost/nodeone/customers/6 HTTP/1.1
content-type: application/json

{
    "name": "Katie",
    "course": "Dog Training",
    "active": 1,
    "officeId": 1
}

###
GET http://localhost/nodeone/customers

###
GET http://localhost/nodeone/customers/6